# Form implementation generated from reading ui file 'controlboard.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import data_loader


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1402, 705)
        mainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1401, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.data_module = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.data_module.setContentsMargins(0, 0, 0, 0)
        self.data_module.setObjectName("data_module")
        self.data_module_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_module_label.sizePolicy().hasHeightForWidth())
        self.data_module_label.setSizePolicy(sizePolicy)
        self.data_module_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.data_module_label.setObjectName("data_module_label")
        self.data_module.addWidget(self.data_module_label)
        self.lfs_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfs_button.sizePolicy().hasHeightForWidth())
        self.lfs_button.setSizePolicy(sizePolicy)
        self.lfs_button.setObjectName("lfs_button")
        self.data_module.addWidget(self.lfs_button)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 220, 591, 451))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.plotter_module = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.plotter_module.setContentsMargins(0, 0, 0, 0)
        self.plotter_module.setObjectName("plotter_module")
        self.plotter_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.plotter_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.plotter_label.setObjectName("plotter_label")
        self.plotter_module.addWidget(self.plotter_label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(590, 220, 811, 451))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.trainer_module = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.trainer_module.setContentsMargins(0, 0, 0, 0)
        self.trainer_module.setObjectName("trainer_module")
        self.trainer_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.trainer_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.trainer_label.setObjectName("trainer_label")
        self.trainer_module.addWidget(self.trainer_label)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 670, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        # i added
        self.lfs_button.clicked.connect(self.lfs_button_called)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "pipeline controlboard"))
        self.data_module_label.setText(_translate("mainWindow", "data loader"))
        self.lfs_button.setText(_translate("mainWindow", "load available files"))
        self.plotter_label.setText(_translate("mainWindow", "plotter"))
        self.trainer_label.setText(_translate("mainWindow", "trainer"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))

    def lfs_button_called(self):
        files = data_loader.find_files()
        print(files)


import sys
from PyQt6.QtWidgets import *


class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.ui = Ui_mainWindow()
        self.ui.setupUi(self)


if __name__ == '__main__':
    app = QApplication([])
    window = MainWindow()
    window.show()
    sys.exit(app.exec())